reset
echo -e "\e[1;32;40m\e[0m"
echo -e "\e[1;32;5m                         ==== DTAS (Datawarehouse Test Automation Suite) ====                          \e[0m"
echo -e "\e[1;32;40m\e[0m"
echo -e "\e[1;32;5m  File Comparision: \e[0m"
echo -e "\e[1;32;40m    For File comparison enter 1 \e[0m"
echo -e "\e[1;32;5m  File Transformations: \e[0m"
echo -e "\e[1;32;40m    For converting pipe delimited to CSV file enter 2 \e[0m"
echo -e "\e[1;32;40m    For converting pipe delimited to excel enter 3 \e[0m"
echo -e "\e[1;32;40m    For converting convert fixed width to pipe delimited enter 4 \e[0m"
echo -e "\e[1;32;5m  Data Unload/Upload utilities: \e[0m"
echo -e "\e[1;32;40m    For table (TERADATA/DB2) unload (DB2 unload tested on informatica 76/84 server only) enter 5 \e[0m"
echo -e "\e[1;32;40m    For load file in teradata using BTEQ enter 6 \e[0m"
echo -e "\e[1;32;40m    For Unloading data from Hive to pipe dilimited file (support JSON/PARQUET/AVRO/CSV formats) enter 7 \e[0m"
echo -e "\e[1;32;40m    For Oracle unload (tested on informatica 76/84 server only) enter 8 \e[0m"
echo -e "\e[1;32;40m    For Oracle unload from two databases enter 9 \e[0m"
echo -e "\e[1;32;40m    Load file in DB2/Oracle - future development ( In progress ) \e[0m"
echo -e "\e[1;32;5m  File Processing utilities: \e[0m"
echo -e "\e[1;32;40m    For getting linenumber in file  enter 10 \e[0m"
echo -e "\e[1;32;40m    For  dropping colums from file enter 11 \e[0m"
echo -e "\e[1;32;5m  Database Utilities: \e[0m"
echo -e "\e[1;32;40m    For Getting  position number and field details teradata enter 12 \e[0m"
echo -e "\e[1;32;40m    For Getting position number and field details hive enter 13 \e[0m"
echo -e "\e[1;32;40m    For Housekeeping enter 13 \e[0m"
echo -e "\e[1;32;40m    For exit enter 0 \e[0m"
echo -e "\e[1;32;5m
                                                                        \e[0m"                               