#!/usr/bin/perl
print "** In case of any issues get in touch with Alok Nath (Alok.nath\@company.com)**\n\n";
print "Choose one of the below options:\n 1 for Teradata table unload\n 2 for db2 table unload \n 0 to exit\n Enter the option: ";
my $useroption = <STDIN>;
chomp $useroption;
 if ($useroption eq 0){
	exit 0;
	}
elsif($useroption ==1){
		print "Please enter the databaseame.tablename \n";
		my $filename = <STDIN>;
		print "$filename";
		chop($filename);
		$val1=".EXPORT REPORT FILE=$filename".".txt\n";
		$val2="select * from $filename\;\n";
		print $val1;
		print "$val2";
		my $path=`pwd`;
		chomp $path;
		open(WR1,">$path/CODE/Query_append.txt");
		print  WR1 ("$val1");
		print WR1  ("$val2");
		close WR1;
		$cmd0="cat $path/CODE/td_pre.txt $path/CODE/Query_append.txt> td.txt";
		system ("$cmd0");
		$cmd1="rm -rf $path/CODE/$filename.txt";
		$cmd2="bteq<td.txt";
		system ("$cmd1 && $cmd2");
		$cmd3="perl -i -pe 's/(?<=\|) +|^ +//g' $filename.txt";
		system ("$cmd3");
		`rm td.txt Query_append.txt`;
		print "Table has been sucessfully unloaded as $filename.txt\n";
	}
elsif($useroption ==2){
		print "Please enter the creator.tablename \n";
		my $NAME = <STDIN>;
		chomp $NAME;
		$cmd1=". /home/db2client/v97fp5/sqllib/db2profile";
		$cmd2="db2 connect to RDSA user userid1234567 using n###17";
		$dte="DATE";
		$cmd4="awk 'NR > 7 { print }' db2table_structure.txt |head -n -1 | cut -d ' ' -f5>db2_datatype.txt";
		$cmd5="awk 'NR > 7 { print }' db2table_structure.txt |head -n -1 | cut -c 37-67 |awk '{\$1=\$1}{ print }'>db2_column.txt";
		$cmd3="db2 \"describe output select * from $NAME\">db2table_structure.txt";
		system ("$cmd1 && $cmd2 && $cmd3" );
		system ("$cmd4");
		system ("$cmd5");
		$cmd6="rm -rf pre_query1_db2.txt";
		system ("$cmd6");
		open my $fh1, '<', 'db2_column.txt';
		open my $fh2, '<', 'db2_datatype.txt';
		while (!eof($fh1) && !eof($fh2)) {
		chomp(my $line1 = <$fh1>);
		chomp(my $line2 = <$fh2>);
		$line_data=$line2 eq 'DATE' ? "CHAR($line1".",EUR)"." " : "$line1"." ";
		open (WR2,">>pre_query1_db2.txt");
		print WR2 "$line_data\n";
		close WR2;
		}
		$cmd10="cat db2_column.txt| wc -l >count.txt";
		system ("$cmd10");
		$count=`cat count.txt`;
		print "$count\n";
		for (my $i=1; $i<=$count;) {
		$filePath1= "pre_query1_db2.txt";
		$lineWanted1 = $i;
		open my $fh4, '<', 'pre_query1_db2.txt';
		my $line1;
		while( <$fh4> ) {
				if( $. == $lineWanted1 ) {
				$line1 = $_;
				last;
		  }
	   }
		#print $line1;
		chomp ($line1);
		$cmd9="db2 \"Select TRIM(".$line1.") from $NAME\">unload1_temp$i.txt";
		system ("$cmd1 && $cmd2 && $cmd9 ");
		sleep 10;
		$cmd10="awk 'NR > 3 { print }' unload1_temp$i.txt | head -n -3 > unload_temp$i.txt";
		open (WR3,">>unload_filenames_sequence1.txt");
		print WR3 "unload_temp$i.txt\n";
		close WR3;
		#system ("$cmd10");
		$i++;
		}
		for (my $j=1; $j<=$count;) {
		$cmd10="awk 'NR > 3 { print }' unload1_temp$j.txt | head -n -3 > unload_temp$j.txt";
		system ("$cmd10");
		$j++;
		}
		$cmd12= "cat unload_filenames_sequence1.txt | xargs > unload_filenames_sequence.txt";
		system ("$cmd12");
		$file_paste = `cat unload_filenames_sequence.txt`;
		chomp $file_paste;
		$cmd11="paste $file_paste | sed 's/ //g' | sed 's/\\t/|/g' | sed 's/|-|/||/g' > final_$NAME.txt";
		system ("$cmd11");
		$cmd15="sed -i 's/|-/| /g' final_$NAME.txt";
		$cmd16="sed -i 's/-|/ |/g' final_$NAME.txt";
		system ("$cmd15");
		system ("$cmd16");
		$cmd13="rm -rf *unload*_temp*";
		system (" $cmd13 ");
		`rm pre_query1_db2.txt db2table_structure.txt db2_datatype.txt db2_column.txt count.txt`;
		$cmd14="rm -rf unload_filenames_sequence1.txt unload_filenames_sequence.txt";
		system ("$cmd14");
}
else {
	 print "Incorrect option give correct option\n";
	 my $useroption = <STDIN>;
	 }