reset
echo  "\e[1;32;m\e[m"
echo  "\e[1;32;42m                         ==== DTAS (Datawarehouse Test Automation Suite) ====                          \e[m"
echo  "\e[1;32;42m\e[m"
echo  "\e[1;32;32m  File Comparision: \e[m"
echo  "\e[1;32;m    For File comparison enter 1 \e[m"
echo  "\e[1;32;32m  File Transformations: \e[m"
echo  "\e[1;32;m    For converting pipe delimited to CSV file enter 2 \e[m"
echo  "\e[1;32;m    For converting pipe delimited to excel enter 3 \e[m"
echo  "\e[1;32;m    For converting convert fixed width to pipe delimited enter 4 \e[m"
echo  "\e[1;32;32m  Data Unload/Upload utilities: \e[m"
echo  "\e[1;32;m    For table (TERADATA/DB2) unload (DB2 unload tested on informatica 76/84 server only) enter 5 \e[m"
echo  "\e[1;32;m    For load file in teradata using BTEQ enter 6 \e[m"
echo  "\e[1;32;m    For Unloading data from Hive to pipe dilimited file (support JSON/PARQUET/AVRO/CSV formats) enter 7 \e[m"
echo  "\e[1;32;m    For Oracle unload (tested on informatica 76/84 server only) enter 8 \e[m"
echo  "\e[1;32;m    For Oracle unload from two databases enter 9 \e[m"
echo  "\e[1;32;m    Load file in DB2/Oracle - future development ( In progress ) \e[m"
echo  "\e[1;32;32m  File Processing utilities: \e[m"
echo  "\e[1;32;m    For getting linenumber in file  enter 10 \e[m"
echo  "\e[1;32;m    For  dropping colums from file enter 11 \e[m"
echo  "\e[1;32;32m  Database Utilities: \e[m"
echo  "\e[1;32;m    For Getting  position number and field details teradata enter 12 \e[m"
echo  "\e[1;32;m    For Getting position number and field details hive enter 13 \e[m"
echo  "\e[1;32;m    For Housekeeping enter 14 \e[m"
echo  "\e[1;32;32m  Mainframe DB2 file create Utilities: \e[m"
echo  "\e[1;32;m    For creating Db2 unload monthly files  enter 15 \e[m"
echo  "\e[1;32;m    For setting ID and Passwords  enter 16 \e[m"
echo  "\e[1;32;m    For db2 unload using portable program works on any server 17 \e[m"
echo  "\e[1;32;m    For exit enter 0 \e[m"
echo  "\e[1;32;42m                                                                                                       \e[m"